name: Mirror to Bitbucket

on:
  push:
    branches:
      - carbon

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$BITBUCKET_SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
      - name: Update known hosts
        run: ssh-keyscan bitbucket.org >> ~/.ssh/known_hosts

      - name: Add Bitbucket Remote
        run: |
          git remote add bitbucket git@bitbucket.org:kvpafrica/fineract-backend-cba.git
          git fetch bitbucket --prune

      - name: Mirror to Bitbucket
        run: |
          git push --mirror bitbucket
